name: Kits
api: 3.0.0
main: kits\Main
version: 1.9
description: Get A Kit!

author: survanetwork
description: A Super Simple Plugin That Gives Kits!
website: https://github.com/joshuasing/Kits

commands:
  starterkit:
  usage: /starterkit
  description: Get a Starter Kit!
